worker_processes 1;

events { worker_connections 1024; }

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;

    upstream security {
        server security:5000;
    }

    upstream uploader {
        server uploader:3000;
    }

    upstream minio {
        server minio:9000;
    }

    server {
        listen 80;

        # Внутренняя проверка токена
        location = /auth {
            internal;
            proxy_pass http://security/v1/token/validation;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header X-Original-URI $request_uri;
            proxy_set_header Authorization $http_authorization;
        }

        # Регистрация
        location /register {
            proxy_pass http://security/v1/user;
        }

        # Получение токена
        location /token {
            proxy_pass http://security/v1/token;
        }

        # Получение информации о пользователе (с авторизацией)
        location /user {
            proxy_set_header Authorization $http_authorization;
            auth_request /auth;
            proxy_pass http://security/v1/user;
        }

        # Загрузка изображения
        location /upload {
            proxy_set_header Authorization $http_authorization;
            auth_request /auth;
            proxy_pass http://uploader/v1/upload;
        }

        # Получение изображения
        location /images/ {
            proxy_set_header Authorization $http_authorization;
            auth_request /auth;
            rewrite ^/images/(.*)$ /$1 break;
            proxy_pass http://minio;
        }
    }
}
