
worker_processes 1;
events { worker_connections 1024; }

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;

    upstream security {
        server security:5000;
    }

    upstream uploader {
        server uploader:3000;
    }

    upstream minio {
        server minio:9000;
    }

    server {
        listen 80;

        # Регистрация пользователя
        location = /v1/register {
            proxy_pass http://security/v1/user;
        }

        # Получение токена
        location = /v1/token {
            proxy_pass http://security/v1/token;
        }

        # Проверка токена и получение информации о пользователе
        location = /v1/user {
            internal;
            proxy_pass http://security/v1/user;
        }

        # Проверка токена и проксирование на uploader
        location = /v1/upload {
            auth_request /auth;
            proxy_pass http://uploader/v1/upload;
        }

        # Проверка токена и проксирование к MinIO
        location ~ ^/images/(.*)$ {
            auth_request /auth;
            proxy_pass http://minio/images/$1;
        }

        # Маршрут для внутренней проверки токена
        location = /auth {
            internal;
            proxy_pass http://security/v1/token/validation;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header X-Original-URI $request_uri;
            proxy_set_header Authorization $http_authorization;
        }
    }
}
